name: Build and Push Docker Image

on:
  # Dispara automaticamente quando há push na main
  push:
    branches:
      - master

  # Mantém a opção de disparo manual
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag da imagem (ex: v1.0.0 ou latest)"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/janio-front:${{ steps.tag.outputs.TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/janio-front:${{ steps.tag.outputs.TAG }}

      - name: Show published image
        run: echo "✅ Image ghcr.io/${{ github.repository_owner }}/janio-front:${{ steps.tag.outputs.TAG }} published successfully!"
